FROM node:18-alpine as builder

WORKDIR /usr/src/app

COPY . .

ARG REACT_APP_ADMIN_USERNAME
ARG REACT_APP_ADMIN_PASSWORD
ARG REACT_APP_CLIENT_USERNAME
ARG REACT_APP_CLIENT_PASSWORD

ENV REACT_APP_ADMIN_USERNAME=$REACT_APP_ADMIN_USERNAME
ENV REACT_APP_ADMIN_PASSWORD=$REACT_APP_ADMIN_PASSWORD
ENV REACT_APP_CLIENT_USERNAME=$REACT_APP_CLIENT_USERNAME
ENV REACT_APP_CLIENT_PASSWORD=$REACT_APP_CLIENT_PASSWORD

RUN npm install --legacy-peer-deps
RUN npm run build

FROM nginx

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/app/build /usr/share/nginx/html