export const ImagesBundlesDict: { [id: string] : string; } = {
    'Modular Assembly and Cloning with Ordering'             : require("./bundles/Modular Assembly and Cloning with Ordering.png"),
    'Modular Assembly and Cloning with Provided DNA'         : require("./bundles/Modular Assembly and Cloning with Provided DNA.png"),
    'RNA Sequencing'                                         : require("./bundles/RNA Sequencing.png"),
    'Protein Production, Purification, and Induction Bundle' : require("./bundles/Protein Production, Purification, and Induction Bundle.png"),
    'DNA/RNA Extraction and qPCR'                            : require("./bundles/DNA Exract and qPCR.png"),
    'Gibson Assembly and Cloning with Provided DNA'          : require("./bundles/Gibson Assem and Cloning.png"),
    'Gibson Assembly and Cloning with Ordering'              : require("./bundles/Gibson Assem and Cloning.png"),
    'Library Prep (16S,ITS)'                                 : require("./bundles/RNA Sequencing.png"),
  };

export const ImagesServicesDict: { [id: string] : string; } = {
    'Cell Culture Induction and Selection'                  : require("./services/Cell Culture.png"),
    'Cell Lysate Production'                                : require("./services/Cell Lysate Production.png"),
    'Transformation'                                        : require("./services/Cell Transformation.png"),
    'Clean Up and Concentrate DNA'                          : require("./services/Clean Up and Concentrate DNA.png"),
    'Design and Order Primers'                              : require("./services/Design and Order Primers from Third Party.png"),
    'Digest with Dpn1'                                      : require("./services/Digest with Dpn1.png"),
    'DNA RNA Ethanol Precipitation'                         : require("./services/DNA RNA Ethanol Precipitation.png"),
    'DNA RNA Extraction'                                    : require("./services/DNA RNA Extraction.png"),
    'Gibson Assembly'                                       : require("./services/Gibson Assembly.png"),
    'Glycerol Stock Storage'                                : require("./services/Glycerol Stock Creation.png"),
    'Fragment Analyzer'                                     : require("./services/Library.png"),
    'Modular Cloning'                                       : require("./services/Modular Cloning.png"),
    'Order Gene Fragment'                                   : require("./services/Ordering DNA.png"),
    'Overnight Innoculums of Bacteria Cell Culture Storage' : require("./services/Overnight Cell Culture.png"),
    'Gel Electrophoresis'                                   : require("./services/Perform Gel Electrophoresis.png"),
    'PCR'                                                   : require("./services/Perform PCR.png"),
    'qPCR'                                                  : require("./services/qPCR.png"),
    'Spectrophotometric Assay'                              : require("./services/Spectrophotometric.png"),
    'Miniprep and Glycerol Stock'                           : require("./services/Plasmid DNA Miniprep.png"),
    'Plasmid, DNA fragment, or oligo storage'               : require("./services/Plasmid DNA RNA Fragments and Oligos Storage.png"),
    'Overnight Inoculum'                                    : require("./services/Prepare Liquid Overnight.png"),
    'Protein Production and Purification from Cell Lysate'  : require("./services/Protein Production.png"),
    'Purify DNA from Agarose Gel Extraction'                : require("./services/Purify DNA from Agarose Gel Extraction.png"),
    'Rehydrate Primers'                                     : require("./services/Rehydrate DNA Oligo.png"),
    'Restriction Digest'                                    : require("./services/Restriction Digestion.png"),
    'Restriction Ligation'                                  : require("./services/Restriction Ligation.png"),
    'Next Generation Sequencing'                            : require("./services/RNA-Sequencing.png"),
    'Send Sample to Sequencing'                             : require("./services/Send Sample to Sequencing.png")
};
